
-- Create the prompts table
CREATE TABLE public.prompts (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  prompt_text TEXT NOT NULL,
  platform TEXT NOT NULL,
  category TEXT NOT NULL,
  example_image_url TEXT,
  usage_tips TEXT,
  credit_cost INTEGER NOT NULL DEFAULT 1,
  is_premium BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Add comments to columns for clarity
COMMENT ON TABLE public.prompts IS 'Stores the prompts for the prompt library.';
COMMENT ON COLUMN public.prompts.title IS 'The title of the prompt.';
COMMENT ON COLUMN public.prompts.prompt_text IS 'The main content of the prompt.';
COMMENT ON COLUMN public.prompts.platform IS 'The AI platform the prompt is for (e.g., Midjourney, ChatGPT).';
COMMENT ON COLUMN public.prompts.category IS 'The category of the prompt (e.g., Art, Marketing).';
COMMENT ON COLUMN public.prompts.example_image_url IS 'URL for an example image generated by the prompt.';
COMMENT ON COLUMN public.prompts.usage_tips IS 'Optional tips on how to use the prompt effectively.';
COMMENT ON COLUMN public.prompts.credit_cost IS 'How many credits it costs to use this prompt.';
COMMENT ON COLUMN public.prompts.is_premium IS 'Whether the prompt is for premium subscribers only.';
COMMENT ON COLUMN public.prompts.created_at IS 'When the prompt was created.';

-- Enable Row Level Security
ALTER TABLE public.prompts ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow public read access to all prompts
CREATE POLICY "Prompts are viewable by everyone."
  ON public.prompts FOR SELECT
  USING (true);
