// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxvlypjfdtskojrxokwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dmx5cGpmZHRza29qcnhva3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjUxOTEsImV4cCI6MjA2NTUwMTE5MX0.py0nj23Y8RlLB8_pL_2B7A6rOdbg-P6p_yPgDW0SmdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);